/**
 * Shared types for the event-driven wallet co-pilot agent layer.
 *
 * SAFETY: ProposedAction is the ONLY output format for all agents.
 * Agents never sign transactions — they produce unsigned payloads only.
 */

// ─── Agent Identifiers ──────────────────────────────────

export type AgentId = 'security' | 'uniswap' | 'governance';

// ─── Risk Levels ────────────────────────────────────────

export type RiskLevel = 'low' | 'medium' | 'high';

// ─── Action Types ──────────────────────────────────────

export type ActionType = 'SWAP' | 'REVOKE' | 'INFO';

// ─── ProposedAction ─────────────────────────────────────
// Canonical output format returned by every agent.

export interface ProposedAction {
  /** Unique identifier (UUID) */
  id: string;
  /** Which agent produced this action */
  agent: AgentId;
  /** Short human-readable title */
  title: string;
  /** One-sentence summary of the action */
  summary: string;
  /** Reasoning bullets (max 3, generated by LLM or deterministic) */
  reasoning: string[];
  /** Risk assessment */
  risk: RiskLevel;
  /** The category of action being proposed */
  actionType: ActionType;
  /** Agent-specific payload (unsigned tx data, token addresses, etc.) */
  payload: Record<string, unknown>;
  /** Timestamp when proposal was created (ms since epoch) */
  createdAt: number;
  /** Optional expiry timestamp (ms since epoch) */
  expiresAt?: number;
}

// ─── Event Types for QuickNode Streams ──────────────────

export type StreamEventType = 'Approval' | 'Transfer' | 'Unknown';

export interface StreamEvent {
  id: string;
  eventType: StreamEventType;
  timestamp: number;
  blockNumber?: number;
  transactionHash?: string;
  /** Decoded event data — shape depends on eventType */
  data: Record<string, unknown>;
  chainId: number;
}

// ─── Wallet Balance ─────────────────────────────────────

export interface TokenBalance {
  /** Token contract address (0x0...0 for native ETH) */
  token: string;
  /** Token symbol (e.g. "ETH", "USDC") */
  symbol: string;
  /** Balance in wei (string to avoid precision loss) */
  balanceWei: string;
  /** Decimals for this token */
  decimals: number;
  /** USD value (optional, may be 0 if price unavailable) */
  usdValue?: number;
}

export interface WalletPortfolio {
  wallet: string;
  chainId: number;
  balances: TokenBalance[];
  totalUsdValue: number;
  /** Concentration percentages keyed by token symbol */
  concentrations: Record<string, number>;
}

// ─── Uniswap Quote ─────────────────────────────────────

export interface UniswapQuote {
  tokenIn: string;
  tokenOut: string;
  amountIn: string;
  amountOut: string;
  slippageBps: number;
  priceImpactBps?: number;
  route?: string;
  expiresAt: number;
}

// ─── Uniswap Swap Transaction Payload ───────────────────
// Unsigned tx returned to the client for wallet-side signing.

export interface UniswapSwapTx {
  /** Contract to call (Uniswap router) */
  to: string;
  /** ABI-encoded swap calldata */
  data: string;
  /** Native value to send (hex string, e.g. "0x0") */
  value: string;
  /** Target chain */
  chainId: number;
  /** Optional gas fields — included when Uniswap provides them */
  gasLimit?: string;
  maxFeePerGas?: string;
  maxPriorityFeePerGas?: string;
}

// ─── Governance Proposal Input ──────────────────────────

export interface GovernanceProposalInput {
  proposalId: string;
  title: string;
  body: string;
  space?: string;
}

// ─── Gemini LLM Output Shapes ───────────────────────────

export interface SecurityReasoningOutput {
  reasoning: string[];
}

export interface SwapReasoningOutput {
  explanation: string[];
  riskNotes: string[];
}

export interface GovernanceSummaryOutput {
  summary: string;
  risks: string[];
  recommendation: 'FOR' | 'AGAINST' | 'ABSTAIN';
  confidence: number;
}
